#pragma once

//Character
#define MIN_HEALTH 0.f
#define DEFAULT_MAX_HEALTH 100.f
#define MAX_TURNINPLACE_RIGHT 90.f
#define MAX_TURNINPLACE_LEFT -90.f
#define STAND_SPEED 0.f


//Timer
#define DEFAULT_TIMER_RUN .5f
#define DEFAULT_TIMER_SLIDE 1.f
#define DEFAULT_TIMER_OBJECTIVE_UPDATE 1.f
#define DEFAULT_TIMER_OBJECTIVE_UPDATE_HUD (DEFAULT_TIMER_OBJECTIVE_UPDATE + 0.5f)

//First Person
#define DISTANCE_FIRST_PERSON_XAXIS 0.f
#define DISTANCE_FIRST_PERSON_YAXIS 20.f
#define DISTANCE_FIRST_PERSON_ZAXIS -2.f
#define CAMERA_POV_FIRST_PERSON_DEFAULT 120.f

//Third Person
#define DEFAULT_THIRD_PERSON_CHARACTER_POV_SIGHT 150.f
#define DEFAULT_THIRD_PERSON_CHARACTER_POV 220.f
#define DEFAULT_FIRST_PERSON_CHARACTER_POV 0.f


//AI
#define AI_SHOOTING_RANGE_VERY_EASY 300.f
#define AI_SHOOTING_RANGE_EASY 200.f
#define AI_SHOOTING_RANGE_MEDIUM 100.f
#define AI_SHOOTING_RANGE_HARD 50.f
#define NEAR_PLAYER_DISTANCE 1500.f

#define SUSPECT_MAX_TIMER 100.f
#define SUSPECT_MIN_TIMER 0.f
#define SUSPECT_INCREASE_TIMER 1.f

//AI - DistanceFromCharacter

#define DISTANCE_FROM_CHARACTER_MIN 300.f
#define DISTANCE_FROM_CHARACTER_MAX 500.f

//Right Hand Axis
#define StockRollAxis -45.936744
#define StockPitchAxis 40.f
#define StockYawAxis 1.f
#define DEFAULT_ZERO_AXIS 0.f

//Game Mode: Spawn
#define DEFAULT_SPAWN_TIMER 30.f
#define DEFAULT_SPAWN_TIMER_EASY 10.f
#define DEFAULT_SPAWN_TIMER_MEDIUM 20.f
#define DEFAULT_SPAWN_TIMER_HARD 30.f

#define MAX_SPAWN_CHARACTER 50
//#define MAX_SPAWN_WEAPON_ITEM 30
#define MAX_SPAWN_WEAPON 0
#define MAX_SPAWN_HEALTH 10
#define MAX_SPAWN_AMMO 20

#define MAX_SPAWN_WEAPON_ITEM (MAX_SPAWN_WEAPON + MAX_SPAWN_HEALTH + MAX_SPAWN_AMMO) + 50

//Projectile
#define DEFAULT_DAMAGE_OVERALL 20.f
#define DEFAULT_DAMAGE_INNER_RADIUS 200.f
#define DEFAULT_DAMAGE_OUTER_RADIUS 500.f
#define DEFAULT_DAMAGE_FALLOFF 1.f
#define DEFAULT_SPEED 5000.f


//Weapon 
#define DEFAULT_ANGLE_AIMING_YAW -10.3f
#define DEFAULT_ANGLE_AIMING_PITCH  2.15f
#define WEAPON_MAX_RANGE 10000.f
#define MELEE_DAMAGE 5.f

#define TRACE_LENGTH 80000.f //calculate weapon shoot range

//Jump
#define DEFAULT_FALLING_TIMER 1.5f;

//Projectile
#define DEFAULT_HEIGHT_PROJECTILE_HORIZON 1.45f //character height from the game (meter)
#define DEFAUNT_GRAVITY 9.81

//Custom Depth
#define CUSTOM_DEPTH_PURPLE 250
#define CUSTOM_DEPTH_BLUE 251
#define CUSTOM_DEPTH_TAN 252


//Stat (Widget)
#define WEAPON_MAX_DAMAGE_STAT 100.f
#define WEAPON_MAX_RANGE_STAT 2.f //kilometer
#define WEAPON_MAX_RECOIL_STAT 10.f
#define WEAPON_MAX_RATEOFFIRE_STAT 1.f
#define WEAPON_MAX_RANGE_MELEE_STAT 3.f //meter